version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      - run: apt-get update; apt-get install curl
      - run: curl -sSf https://nim-lang.org/choosenim/init.sh | sh -s -- -y
      - run: choosenim 0.19.2
      - run: nimble test
