version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      # - run: apt-get update; apt-get install -y curl
      # - run: curl -sSf https://nim-lang.org/choosenim/init.sh | sh -s -- -y
      # - run: choosenim 1.0.2
      - run: nimble test
